### ISSUE TITLE
Django 2.0 compatibility issue with urlresolvers

### ISSUE THREAD

**Issue by ajira86** [kyokenn/djradicale#11]
Hi,

I just upgraded a project to Django 2.0 today and got an error with urlresolvers importation from Django. Apparently the urlresolvers call is deprecated since Django 1.10 and is dropped from 2.0

```
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/djradicale/models.py", line 21, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
```
```
$ grep "urlresolver" -nr .
./djradicale/models.py:21:from django.core.urlresolvers import reverse
./djradicale/views.py:22:from django.core.urlresolvers import reverse
./djradicale/tests/test_caldav.py:18:from django.core.urlresolvers import reverse
./djradicale/tests/test_carddav.py:18:from django.core.urlresolvers import reverse
```
Ok, four entries to be replaced with ```from django.urls import reverse```.
I'll prepare a PR if I have time tonight.

**Comment by ajira86** [comment]
There are a multiple of things to do to upgrade to Django 2.0, I prepare things from the branch https://github.com/ajira86/djradicale/tree/django2
