### ISSUE TITLE
Multistatus Response

### ISSUE THREAD

**Issue by cs-stainly** [kyokenn/djradicale#4]
I am currently stuck with a multistatus response and don't know my way around it.
I tried it with Calendar under Mac and iPhone and whenever I add an Event I get a multistatus response. When I change the calendar color, it gets successfully synchronized.

Any help?

**Comment by kyokenn** [comment]
Multistatus response is just a normal WebDAV response. You have to look to the contents of the response. Could you provide some logs?

**Comment by cs-stainly** [comment]
I used Calendar from MAC to test the server.
The logger output below is produced when I try to add an event.

Could you maybe provide an example of the "path" and "parent path" when creating a collection?

Here is the logger output:

```
Authentication type is custom
PUT request at /pim/admin/calendar.ics/52E7CA12-3548-42D1-B84C-892B583E7590.ics received
Request headers:
{'CONTENT_LENGTH': '752',
 'CONTENT_TYPE': 'text/calendar',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-us',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_HOST': '192.168.178.23:5000',
 'HTTP_IF_NONE_MATCH': '*',
 'HTTP_USER_AGENT': 'Mac+OS+X/10.11.5 (15F34) CalendarAgent/361.2',
 'PATH_INFO': '/pim/admin/calendar.ics/52E7CA12-3548-42D1-B84C-892B583E7590.ics',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '192.168.178.31',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PUT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'Loki',
 'SERVER_PORT': '5000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=5>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
Sanitized path: /admin/calendar.ics/52E7CA12-3548-42D1-B84C-892B583E7590.ics
Rights type 'djradicale.rights.django'
Test if ':admin/calendar.ics' matches against '.*:^/[a-zA-Z0-9\.\-_]+\.(vcf|ics)$' from section 'rw'
Section 'rw' does not match
Test if ':admin/calendar.ics' matches against '.*:^$' from section 'rw-root'
Section 'rw-root' does not match
Anonymous has NO read access to collection admin/calendar.ics/
Rights type 'djradicale.rights.django'
Test if ':admin/calendar.ics' matches against '.*:^/[a-zA-Z0-9\.\-_]+\.(vcf|ics)$' from section 'rw'
Section 'rw' does not match
Test if ':admin/calendar.ics' matches against '.*:^$' from section 'rw-root'
Section 'rw-root' does not match
Anonymous has NO write access to collection admin/calendar.ics/
Request content:
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//Mac OS X 10.11.5//EN
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
DTSTART:19810329T020000
TZNAME:GMT+2
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
DTSTART:19961027T030000
TZNAME:GMT+1
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20160704T105846Z
UID:52E7CA12-3548-42D1-B84C-892B583E7590
DTEND;TZID=Europe/Berlin:20160627T030000
TRANSP:OPAQUE
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
SUMMARY:New Event
DTSTART;TZID=Europe/Berlin:20160627T020000
DTSTAMP:20160704T105857Z
SEQUENCE:0
END:VEVENT
END:VCALENDAR

Anonymous user refused
Answer status: 401 Unauthorized
[04/Jul/2016 12:59:00] "PUT /pim/admin/calendar.ics/52E7CA12-3548-42D1-B84C-892B583E7590.ics HTTP/1.1" 401 0


Authentication type is custom
PUT request at /pim/admin/calendar.ics/52E7CA12-3548-42D1-B84C-892B583E7590.ics received
Request headers:
{'CONTENT_LENGTH': '752',
 'CONTENT_TYPE': 'text/calendar',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-us',
 'HTTP_AUTHORIZATION': 'Basic YWRtaW46aGFtYnVyZzg5',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_HOST': '192.168.178.23:5000',
 'HTTP_IF_NONE_MATCH': '*',
 'HTTP_USER_AGENT': 'Mac+OS+X/10.11.5 (15F34) CalendarAgent/361.2',
 'PATH_INFO': '/pim/admin/calendar.ics/52E7CA12-3548-42D1-B84C-892B583E7590.ics',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '192.168.178.31',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PUT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'Loki',
 'SERVER_PORT': '5000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=5>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
Sanitized path: /admin/calendar.ics/52E7CA12-3548-42D1-B84C-892B583E7590.ics
Rights type 'djradicale.rights.django'
Test if 'admin:admin/calendar.ics' matches against '.*:^admin/[a-zA-Z0-9\.\-_]+\.(vcf|ics)$' from section 'rw'
Section 'rw' matches
admin has read access to collection admin/calendar.ics/
Rights type 'djradicale.rights.django'
Test if 'admin:admin/calendar.ics' matches against '.*:^admin/[a-zA-Z0-9\.\-_]+\.(vcf|ics)$' from section 'rw'
Section 'rw' matches
admin has write access to collection admin/calendar.ics/
Request content:
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//Mac OS X 10.11.5//EN
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
DTSTART:19810329T020000
TZNAME:GMT+2
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
DTSTART:19961027T030000
TZNAME:GMT+1
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20160704T105846Z
UID:52E7CA12-3548-42D1-B84C-892B583E7590
DTEND;TZID=Europe/Berlin:20160627T030000
TRANSP:OPAQUE
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
SUMMARY:New Event
DTSTART;TZID=Europe/Berlin:20160627T020000
DTSTAMP:20160704T105857Z
SEQUENCE:0
END:VEVENT
END:VCALENDAR

Answer status: 201 Created
[04/Jul/2016 12:59:00] "PUT /pim/admin/calendar.ics/52E7CA12-3548-42D1-B84C-892B583E7590.ics HTTP/1.1" 201 0
```

**Comment by kyokenn** [comment]
For collection "/pim/admin/calendar.ics/":
path = admin/calendar.ics
parent_path = admin
Btw, why do you need them? Are you trying to create a collection on the server without using a client?

The logs looks fine for me. Looks like the event was created.

**Comment by cs-stainly** [comment]
Yes I was. Because even though it said it created the event it didn't.

I resolved my problem with the creation of events by changing line 36 in djradicale.storage.django from
`components = [i for i in items if isinstance(i, ical.Component)]`
to
`components = [items[i] for i in items if isinstance(items[i], ical.Component)]`

the original line looped through the keys of "items" but I believe I need the values in the components list

**Comment by cs-stainly** [comment]
I can create collections and events but I get an error when I want to change the event.

```
Internal Server Error: /pim/cwitt/cal.ics/6177E4B1-C595-4FE5-8CF3-C8833C7B369B.ics
Traceback (most recent call last):
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/djradicale/views.py", line 62, in dispatch
    answer = self(request.META, response.start_response)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/radicale/__init__.py", line 332, in __call__
    user)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/radicale/__init__.py", line 577, in do_PUT
    item = collection.items.get(item_name)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/radicale/ical.py", line 464, in items
    self.text, (Event, Todo, Journal, Card, Timezone))
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/djradicale/storage/django.py", line 63, in text
    self.tag, self.headers, sorted(items, key=lambda x: x.name))
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/djradicale/storage/django.py", line 63, in <lambda>
    self.tag, self.headers, sorted(items, key=lambda x: x.name))
AttributeError: 'str' object has no attribute 'name'
```

**Comment by kyokenn** [comment]
What version of Radicale are you using?

**Comment by cs-stainly** [comment]
I use Radicale==1.1.1

**Comment by kyokenn** [comment]
I has ported a project to latest Radicale (1.1.1). You can try a new version. Let me know if it working.

**Comment by cs-stainly** [comment]
I tested it today. It works like a charm. Thank you very much!
