### ISSUE TITLE
Items do not update properly

### ISSUE THREAD

**Issue by cs-stainly** [kyokenn/djradicale#5]
Since the update to Radicale 1.1.1 I can create and delete events and synchronize them with the server but updating the event has no effect on the stored item on the server.

Example:
1.) I created an event for today starting at 6pm and ending at 8pm.
2.) I synchronized a mobile device with the server and got that event.
3.) I changed the title, and the start and end date and saved it. 

The server responds with OK and the logger outputs the correct (new) SUMMARY, DTSTART, and DTEND. The corresponding item in the DB is deleted and a new one is created.
Unfortunately the new event, that is the updated event, has the same (old) values for SUMMARY, DTSTART, and DTEND.

**Comment by kyokenn** [comment]
This should be fixed in latest version.

**Comment by cs-stainly** [comment]
Hi Okami-1,
first off: Thank you a lot that you respond so fast and that you work on fixing this.

I believe I do something wrong. I upgraded to djradicale 0.0.9 and tried again to create, change, and delete a calendar item.

I still can create items but changing it or trying to delete it causes internal server errors.

The Stacktrace:

```
Internal Server Error: /pim/admin/calendar.ics/20160712T122112Z-6119-1000-1240-0@Loki
Traceback (most recent call last):
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/djradicale/views.py", line 62, in dispatch
    answer = self(request.META, response.start_response)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/radicale/__init__.py", line 332, in __call__
    user)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/radicale/__init__.py", line 588, in do_PUT
    xmlutils.put(environ["PATH_INFO"], content, collection)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/radicale/xmlutils.py", line 450, in put
    collection.replace(name, ical_request)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/djradicale/storage/django.py", line 66, in replace
    collection=collection, name=name)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
djradicale.models.DoesNotExist: DBItem matching query does not exist.
[12/Jul/2016 14:46:05] "PUT /pim/admin/calendar.ics/20160712T122112Z-6119-1000-1240-0@Loki HTTP/1.1" 500 173130
```

Logger output: 
[logger.txt](https://github.com/okami-1/djradicale/files/359319/logger.txt)

**Comment by kyokenn** [comment]
Check your database. Do you have a DBItem with name = "20160712T122112Z-6119-1000-1240-0@Loki" ? Also the DBItem related collection's name should be "admin/calendar.ics".

**Comment by cs-stainly** [comment]
I have a DBItem with the name `20160712T122112Z-6119-1000-1240-0_Loki-20160712T122119Z.ics`
and the related collection is `admin/calendar.ics`

I have no clue why there is no @ symbol in the DBItem name

**Comment by kyokenn** [comment]
But the request URL was "/pim/admin/calendar.ics/20160712T122112Z-6119-1000-1240-0@Loki".
Looks like something wrong with a client. Which client is that? Evolution?

**Comment by cs-stainly** [comment]
Yes, I use Evolution

**Comment by cs-stainly** [comment]
I have the same issue with the apple calendar from iOS 9.

The client requests `/pim/admin/calendar.ics/2B7CD521-F669-47F2-BE26-03152D021754`
The only DBItem I have is `2B7CD521-F669-47F2-BE26-03152D021754.ics`

Do the clients chose the name of the DBItem?

Traceback:

```
Internal Server Error: /pim/admin/calendar.ics/2B7CD521-F669-47F2-BE26-03152D021754
Traceback (most recent call last):
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/djradicale/views.py", line 62, in dispatch
    answer = self(request.META, response.start_response)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/radicale/__init__.py", line 332, in __call__
    user)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/radicale/__init__.py", line 588, in do_PUT
    xmlutils.put(environ["PATH_INFO"], content, collection)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/radicale/xmlutils.py", line 450, in put
    collection.replace(name, ical_request)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/djradicale/storage/django.py", line 66, in replace
    collection=collection, name=name)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/csinhart/atonraenv/env/lib/python3.5/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
djradicale.models.DoesNotExist: DBItem matching query does not exist.
[13/Jul/2016 08:09:36] "PUT /pim/admin/calendar.ics/2B7CD521-F669-47F2-BE26-03152D021754 HTTP/1.1" 500 19794
```

**Comment by cs-stainly** [comment]
When I manually change the name of the DBItem in the database so that there is no `.ics` at the end of the name, then it works with the Calendar app from iOS and that holds apparently also for Evolution.
Evolution was able to change the modified DBItem and the iPhone got the changes.

**Comment by kyokenn** [comment]
The last update broke Radicale serialization, so the X-RADICALE-NAME field was not created.
This field is used to store item's internal name with ".ics" extension.
I had fixed it, and also tested with Thunderbird Lightning and Evolution.

**Comment by cs-stainly** [comment]
Seems to work perfectly now.

Thanks a lot!
